version: "2"
formatters:
  # Enable specific formatter
  enable:
    - gofmt
    - goimports
linters:
  # Enable specific linter
  enable:
# https://golangci-lint.run/usage/linters/#enabled-by-default
#    - errcheck
#    - gosimple
#    - govet
#    - ineffassign
#    - staticcheck
#    - unused
    - gocritic
    - gosec
    - revive
    - bodyclose
  settings:
    staticcheck:
      checks:
        - all
        # Ignore usage of deprecated things, will be removed after frontend resources are using new navigation
        - '-SA1019'
        # Ignore embedded field optimization suggestions
        - '-QF1008'
        # Ignore comment format suggestions
        - '-ST1021'
    gosec:
      excludes:
        - G115
    revive:
      rules:
        # Disable exported type comment requirements
        - name: exported
          disabled: true
  exclusions:
    rules:
      - path: api/v1alpha1/groupversion_info.go
        linters:
          - gofmt
          - goimports
      # Ignore errcheck and gosec issues in test files
      - path: ".*_test\\.go"
        linters:
          - errcheck
          - gosec
issues:
  # Fix found issues (if it's supported by the linter).
  # Default: false
  # fix: true

  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 20
  uniq-by-line: false

run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
