version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - revive
  settings:
    gosec:
      excludes:
        - G115
    staticcheck:
      checks:
        - all
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 20
  uniq-by-line: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - api/v1alpha1/groupversion_info.go
