# Build the manager binary
FROM registry.access.redhat.com/ubi8/go-toolset:1.19.9-2.1687187497 as builder

WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/

USER 0

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o manager main.go

RUN rm main.go
RUN rm -rf api
RUN rm -rf controllers

