apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: inventory
spec:
  envName: env-boot
  title: Inventory
  deploymentRepo: http://test
  API:
    versions:
    - v1
  frontend:
    paths:
    - /apps/inventory
  #   image: quay.io/cloudservices/insights-inventory-frontend:13f80bc
  image: quay.io/redhat-cloud-services/inventory
  navItems:
    - appId: "inventory"
      title: "Inventory"
      href: "/insights/inventory"
      product: "Red Hat Insights"
  module:
    manifestLocation: "/apps/inventory/fed-mods.json"
    # manifestLocation: "/opt/app-root/src/chrome/fed-modules.json"
    modules:
    - id: "inventory"
      module: "./RootApp"
      routes:
      - pathname: /insights/inventory
