apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: inventory
spec:
  # Add fields here
  envName: env-boot
  title: Inventory
  deploymentRepo: http://test
  API:
    versions:
    - v1
  frontend:
    paths:
    - /apps/inventory
  image: quay.io/redhat-cloud-services/inventory
  navItem:
    appId: "inventory"
    title: "Inventory"
    href: "/insights/inventory"
    product: "Red Hat Insights"
  module:
    manifestLocation: "/apps/inventory/fed-mods.json"
    modules:
    - id: "inventory"
      module: "./RootApp"
      routes:
      - pathname: /insights/inventory
