apiVersion: cloud.redhat.com/v1alpha1
kind: Bundle
metadata:
  name: landing-navigation
spec:
  id: landing-navigation
  envName: env-boot
customNav:
  - id: rhel
    appId: dashboard
    title: Red Hat Enterprise Linux
    href: /insights/inventory
