apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    operator-name: frontend-operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      operator-name: frontend-operator
  template:
    metadata:
      labels:
        control-plane: controller-manager
        operator-name: frontend-operator
