apiVersion: v1
kind: Secret
metadata:
  name: single-s3-creds
  labels:
    app.kubernetes.io/component: object-storage-secrets
type: Opaque
stringData:
  aws_access_key_id: "SINGLEBUCKETSECRET"
  aws_secret_access_key: "ABCDEFGHIJKL012345"
  aws_region: "us-west-2"
  endpoint: "https://s3.us-west-2.amazonaws.com"
  bucket: "my-unique-application-bucket"
