apiVersion: v1
kind: Secret
metadata:
  name: shared-s3-credentials
  annotations:
    # The annotation key that pushcache job will look for
    clowder/bucket-names: "app-bucket-1,app-bucket-2,app-bucket-3" 
  labels:
    app.kubernetes.io/component: object-storage-secrets
type: Opaque
stringData:
  aws_access_key_id: "ABCDEFGHIJKL"
  aws_secret_access_key: "shhhhhhhhh/thisissss/sEcRetSeCrEt"
  aws_region: "us-east-1"
  endpoint: "https://s3.amazonaws.com"
