apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: hac-build-service
spec:
  API:
    versions:
      - v1
  assetsPrefix: api/plugins
  deploymentRepo: 'http://github.com/openshift/hac-build-service'
  envName: env-boot
  frontend:
    paths:
      - /api/plugins/hac-build-service
  image: quay.io/cloudservices/hac-build-service-frontend:ae3ca0c
  title: hac-build-service