apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: hac-dev
spec:
  API:
    versions:
      - v1
  assetsPrefix: api/plugins
  deploymentRepo: 'http://github.com/openshift/hac-dev'
  envName: env-boot
  frontend:
    paths:
      - /api/plugins/hac-dev
  image: 'quay.io/cloudservices/hac-dev-frontend:c561bd4'
  title: hac-dev