apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: inventory
spec:
  envName: env-boot
  title: Inventory
  deploymentRepo: https://github.com/RedHatInsights/insights-inventory-frontend
  API:
    versions:
    - v1
  frontend:
    paths:
    - /apps/inventory
  # image: quay.io/cloudservices/insights-inventory-frontend:27803c7
  image: quay.io/tahmidefaz/inventory-frontend-valpop:latest
  pushCacheEnabled: true
  navItems:
    - appId: "inventory"
      title: "Inventory"
      href: "/insights/inventory"
      product: "Red Hat Insights"
  navigationSegments:
    - segmentId: inventory-segment-one
      navItems:
        - id: inventory
          title: Inventory segment
          href: /inventory-foo-var
    - segmentId: nested-segment-two
      navItems:
        - id: nested-two
          title: Nested two
          href: /nested/two
        - id: nested-three
          title: Nested three
          href: /nested/three
  module:
    manifestLocation: "/apps/inventory/fed-mods.json"
    modules:
    - id: "inventory"
      module: "./RootApp"
      routes:
      - pathname: /insights/inventory
