apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: landing
spec:
  # Add fields here
  envName: env-boot
  title: landing
  deploymentRepo: http://test
  feoConfigEnabled: true
  API:
    versions:
    - v1
  frontend:
    paths:
    - /apps/landing
  image: quay.io/redhat-cloud-services/landing
  module:
    manifestLocation: "/apps/landing/fed-mods.json"
    modules:
    - id: "landing"
      module: "./RootApp"
      routes:
      - pathname: /
        exact: true
  searchEntries:
    - id: "landing"
      title: "Landing"
      href: /
      description: "Landing page description"
      alt_title:
        - HCC Home page
        - Home
    - id: "landing-widgets"
      title: "Widget fantastic"
      href: /widgets
      description: "Widget"
  widgetRegistry:
    - scope: "landing"
      module: "./RandomWidget"
      config:
        icon: "CogIcon"
        title: "Random Widget"
      defaults:
        w: 1
        h: 1
        maxH: 2
        minH: 1
  baseWidgetLayouts:
    - name: "landing"
      displayName: "Landing"
      templateConfig:
        sm:
          - w: 2
            h: 2
            cx: 0
            cy: 1
            i: "widget-id-sm"
            static: true
        md:
          - w: 2
            h: 2
            cx: 0
            cy: 1
            i: "widget-id-md"
            static: true
        lg:
          - w: 2
            h: 2
            cx: 0
            cy: 1
            i: "widget-id-lg"
            static: true
        xl:
          - w: 2
            h: 2
            cx: 0
            cy: 1
            i: "widget-id-xl"
            static: true
  serviceTiles:
    - section: automation
      group: ansible
      id: ansible-link
      title: Ansible FOO
      href: /ansible/foo
      description: Ansible FOO description thing
      icon: AnsibleIcon
    - section: iam
      group: iam
      id: iam-link
      title: IAM FOO
      href: /iam
      description: Some Iam thing
      icon: IAMIcon
      isExternal: false
  bundleSegments:
    - segmentId: inventory-partial
      bundleId: insights
      position: 100
      navItems:
        - id: landing
          title: Landing section
          href: /apps/landing
        - id: bar
          title: Some new link
          expandable: true
          routes:
            - id: foo
              title: Foo
              href: /nested/bar
        - id: baz
          title: Some new link
          href: /baz
        - segmentRef:
            frontendName: landing
            segmentId: landing-segment-one
        - segmentRef:
            frontendName: inventory
            segmentId: inventory-segment-one
    - segmentId: segment-one
      bundleId: segmented-bundle
      position: 100
      navItems:
        - id: link-one
          title: Link one classic
          href: /link-one
        - segmentRef:
            segmentId: segment-two-item-one
            frontendName: segmented-app-two
        - id: link-four
          title: Link four classic
          href: /link-four
    - segmentId: nested-segment
      bundleId: segmented-bundle
      position: 200
      navItems:
        - id: expandable
          title: Expandable
          expandable: true
          routes:
            - id: nested-one
              title: Nested one
              href: /nested/one
            - segmentRef:
                segmentId: nested-segment-two
                frontendName: inventory
            - id: nested-four
              title: Nested four
              href: /nested/four
  navigationSegments:
    - segmentId: landing-segment-one
      navItems:
        - id: ssss
          title: SSSS
          href: /ssss
    - segmentId: segment-two-item-one
      navItems:
        - id: link-two
          title: Link two injected
          href: /link-two
        - id: link-three
          title: Link three injected
          href: /link-three

# "spec.baseWidgetLayouts[0].templateConfig.xl[0].true"