apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: landing
spec:
  # Add fields here
  envName: env-boot
  title: landing
  deploymentRepo: http://test
  API:
    versions:
    - v1
  frontend:
    paths:
    - /apps/landing
  image: quay.io/redhat-cloud-services/landing
  module:
    manifestLocation: "/apps/landing/fed-mods.json"
    modules:
    - id: "landing"
      module: "./RootApp"
      routes:
      - pathname: /
        exact: true
    - id: "foobar"
      module: "./RootApp"
      routes:
      - pathname: /foo
        exact: true
  # partials to be inject into specific places
  chromeNavigation:
    - bundle: insights
      # the ID will be prefixed by the metadata.name -> landing.landingTest 
      sectionId: landingTest
      navItems:
        - id: landing
          title: "Landing section"
          href: /apps/landing

