apiVersion: cloud.redhat.com/v1alpha1
kind: Bundle
metadata:
  name: landing-navigation
spec:
  id: landing-navigation
  envName: env-boot
  customNav:
    - groupId: application-services
      title: "Build and Deploy Applications"
      icon: "code"
      navItems:
      - appId: "applicationServices"
        title: "Application and Data Services"
        href: "/application-services/overview"
    - groupId: manage-infrastructure
      title: "Manage Infrastructure"
      icon: "wrench"
      navItems:
      - appId: "openshift"
        title: "Openshift"
        href: "/openshift"
      - title: "Red Hat Enterprise Linux"
        expandable: true
        routes:
        - appId: "dashboard"
          title: "Red Hat Insights"
          href: "/insights/dashboard"
        - appId: "edge"
          title: "Edge Management"
          href: "/edge"
      - appId: "ansibleDashboard"
        title: "Ansible Automation Platform"
        href: "/ansible/ansible-dashboard"
