# Create the AWS bucket secrets in the boot namespace
---
kind: Secret
apiVersion: v1
metadata:
  name: single-s3-creds
  namespace: boot
data:
  aws_access_key_id: bWluaW9hZG1pbg==
  aws_secret_access_key: bWluaW9hZG1pbg==
  aws_region: dXMtd2VzdC0y
  endpoint: bWluaW8tc2VydmljZS5taW5pby1lbnYuc3ZjLmNsdXN0ZXIubG9jYWw=
  bucket: ZnJvbnRlbmQ=
  port: OTAwMA==
