{
 "title": "Frontend Operator Metrics",
 "time": { "from": "2022-01-22T07:31:05.628Z", "to": "2022-02-01T23:31:05.628Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Managed Frontends",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "frontend_managed_frontends" }
   ]
  },
  {
   "title": "Frontend Reconciliations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=~\"frontend|frontendenvironment|bundle\"}[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Pod Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"frontend-operator-system\", container=\"manager\"}[5m]))",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"frontend-operator-system\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"frontend-operator-system\", container=\"manager\"})",
     "legendFormat": "K8s Usage"
    },
    {
     "expr": "avg(go_memstats_alloc_bytes{container=\"manager\", namespace=\"frontend-operator-system\"})",
     "legendFormat": "Alloc Bytes"
    }
   ]
  },
  {
   "title": "CPU Isage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"manager\", namespace=\"clowder-system\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"manager\", namespace=\"clowder-system\"})"
    }
   ]
  }
 ]
}