{
 "title": "Frontend Operator Metrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Push cache job status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_status_failed{namespace=\"frontends\", job_name=~\".*-frontend-pushcache\"} and on(job_name, namespace) (time() - kube_job_created{namespace=\"frontends\", job_name=~\".*-frontend-pushcache\"} < 7200)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Active services",
   "type": "barchart",
   "description": "The per-second rate of HTTP 2xx responses for each service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": " sum by (exported_service) (\n    rate(haproxy_server_http_responses_total{\n      exported_namespace=\"frontends\",\n      code=\"2xx\"\n    }[$__rate_interval])\n  )\n  and\n  sum by (exported_service) (\n    rate(haproxy_server_http_responses_total{\n      exported_namespace=\"frontends\",\n      code=\"2xx\"\n    }[5m])\n  ) > 0.1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Managed Frontends",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "frontend_managed_frontends" }
   ]
  },
  {
   "title": "frontend operator workqueue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "1 - sum(avg_over_time(workqueue_depth{service=\"frontend-operator-controller-manager-metrics-service-non-auth\"}[28d])) by (name)"
    }
   ]
  },
  {
   "title": "Pod Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"frontend-operator-system\", container=\"manager\"}[5m]))",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"frontend-operator-system\", container=\"manager\"})",
     "legendFormat": "K8s Usage"
    },
    {
     "expr": "avg(go_memstats_alloc_bytes{container=\"manager\", namespace=\"frontend-operator-system\"})",
     "legendFormat": "Alloc Bytes"
    }
   ]
  },
  {
   "title": "frontend operator reconciliation time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(avg_over_time(controller_runtime_reconcile_time_seconds_bucket{controller=~\"frontend\", le=\"4\"}[28d])) by (controller) / sum(avg_over_time(controller_runtime_reconcile_time_seconds_bucket{controller=~\"frontend\", le=\"+Inf\"}[28d])) by (controller)"
    }
   ]
  },
  {
   "title": "Frontend Reconciliations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=~\"frontend|frontendenvironment|bundle\"}[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "frontend operator reconciliation error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "(sum by (controller) (avg_over_time(controller_runtime_reconcile_total{controller=~\"frontend\", result=~\"success\"}[28d]))) / (sum by (controller) (avg_over_time(controller_runtime_reconcile_total{controller=~\"frontend\", result=~\"error|success\"}[28d])))"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"frontend-operator-system\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "CPU Isage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 22 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"manager\", namespace=\"clowder-system\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"manager\", namespace=\"clowder-system\"})"
    }
   ]
  }
 ]
}